project_id = "dbalmswufjanxswboxxp"

[functions.extract-address]
verify_jwt = false

[functions.analyze-findings]
verify_jwt = false

[functions.verify-admin-password]
verify_jwt = false

[functions.static-map]
verify_jwt = false
